import AppProvider from "@/lib/AppProvider";
import CommonLayout from "@/lib/layout/common/CommonLayout";
import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <AppProvider>
          <CommonLayout>
            {children}
          </CommonLayout>
        </AppProvider>
      </body>
    </html>
  );
}
